name: Build

on:
  pull_request:
    paths: ['src/**']
  push:
    paths: ['src/**', 'package.json', 'tsconfig.json']
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 21.x
      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dev dependencies
        run: pnpm install

      - name: Prettier check
        run: pnpm check

      - name: Build
        run: pnpm build